/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Dashboard;

import Admin.Game.GameView;
import Admin.User.UserView;
import Admin.Listing.ListingView;
import Admin.Transaksi.TransaksiView;
import entity.user;
import javax.swing.JOptionPane;
import util.Session;

/**
 *
 * @author Bintang K
 */
public class DashboardView extends javax.swing.JFrame {

    /**
     * Creates new form DashboardView
     */
    public DashboardView() {
        initComponents();
        if (Session.getRole().equals("admin")) {
            btnUserView.setVisible(true);
        } else {
            btnUserView.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnGamesView = new javax.swing.JButton();
        btnGenresView = new javax.swing.JButton();
        btnListingsView = new javax.swing.JButton();
        btnReviewsView = new javax.swing.JButton();
        btnTransactView = new javax.swing.JButton();
        btnUserView = new javax.swing.JButton();
        jLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(18, 18, 28));

        btnGamesView.setText("Games");
        btnGamesView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGamesViewActionPerformed(evt);
            }
        });

        btnGenresView.setText("Genres");

        btnListingsView.setText("Listings");
        btnListingsView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnListingsViewMouseClicked(evt);
            }
        });
        btnListingsView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListingsViewActionPerformed(evt);
            }
        });

        btnReviewsView.setText("Reviews");
        btnReviewsView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReviewsViewActionPerformed(evt);
            }
        });

        btnTransactView.setText("Transactions");
        btnTransactView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransactViewActionPerformed(evt);
            }
        });

        btnUserView.setText("Users");
        btnUserView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUserViewMouseClicked(evt);
            }
        });

        jLogout.setText("Logout");
        jLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnListingsView)
                        .addComponent(btnGamesView))
                    .addComponent(btnUserView))
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnGenresView)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addComponent(jLogout))
                    .addComponent(btnReviewsView)
                    .addComponent(btnTransactView))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGamesView)
                    .addComponent(btnGenresView)
                    .addComponent(jLogout))
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListingsView)
                    .addComponent(btnReviewsView))
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTransactView)
                    .addComponent(btnUserView))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUserViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserViewMouseClicked
        // TODO add your handling code here:
        if(Session.getRole().equals("admin")) {
            new UserView().setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Anda bukan admin", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUserViewMouseClicked

    private void btnListingsViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListingsViewMouseClicked
        // TODO add your handling code here:
        new ListingView(Session.getUser()).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnListingsViewMouseClicked

    private void btnReviewsViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReviewsViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReviewsViewActionPerformed

    private void btnTransactViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransactViewActionPerformed
        // TODO add your handling code here:
        new TransaksiView(Session.getUser()).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnTransactViewActionPerformed

    private void btnListingsViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListingsViewActionPerformed
        // TODO add your handling code here:
        new ListingView(Session.getUser()).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnListingsViewActionPerformed

    private void jLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLogoutActionPerformed
        // TODO add your handling code here:
        // 1. Tampilkan konfirmasi biar ga sengaja kepencet logout
        int konfirmasi = JOptionPane.showConfirmDialog(
            this, 
            "Apakah Anda yakin ingin logout?", 
            "Konfirmasi Keluar", 
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE
        );
        
        if (konfirmasi == JOptionPane.YES_OPTION) {
            // 2. Clear data user di class Session (keamanan biar ga kesimpen)
            // Asumsi di class util.Session ada method clear() atau set user jadi null
            Session.clear(); 
            
            // 3. Buka form Login kembali
            // Ganti 'LoginView' sesuai dengan nama class Form Login punyamu
            new Connection.Login().setVisible(true); 
            
            // 4. Tutup halaman Dashboard ini
            this.dispose();
        }
    }//GEN-LAST:event_jLogoutActionPerformed

    private void btnGamesViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGamesViewActionPerformed
        // TODO add your handling code here:
        new GameView(Session.getUser()).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnGamesViewActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGamesView;
    private javax.swing.JButton btnGenresView;
    private javax.swing.JButton btnListingsView;
    private javax.swing.JButton btnReviewsView;
    private javax.swing.JButton btnTransactView;
    private javax.swing.JButton btnUserView;
    private javax.swing.JButton jLogout;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
