/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Dashboard;

import Admin.Genre.GenreView;
import Admin.User.UserView;
import Admin.Listing.ListingView;
import Admin.Transaksi.TransaksiView;
import entity.user;
import javax.swing.JOptionPane;
import util.Session;

/**
 *
 * @author Bintang K
 */
public class DashboardView extends javax.swing.JFrame {

    /**
     * Creates new form DashboardView
     */
    public DashboardView() {
        initComponents();
        if (Session.getUser() != null) {
            String namaUser = Session.getUser().getFullname(); 
            lblWelcome.setText("Halo, " + namaUser);
        }
        if (Session.getRole().equals("admin")) {
            btnUserView.setVisible(true);
        } else {
            btnUserView.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblWelcome = new javax.swing.JLabel();
        btnGamesView = new javax.swing.JButton();
        btnGenresView = new javax.swing.JButton();
        btnListingsView = new javax.swing.JButton();
        btnReviewsView = new javax.swing.JButton();
        btnTransactView = new javax.swing.JButton();
        btnUserView = new javax.swing.JButton();
        jLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dashboard");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(18, 18, 28));

        lblWelcome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(255, 255, 255));
        lblWelcome.setText("Halo, User");

        btnGamesView.setBackground(new java.awt.Color(22, 27, 34));
        btnGamesView.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnGamesView.setForeground(new java.awt.Color(255, 255, 255));
        btnGamesView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/games.png"))); // NOI18N
        btnGamesView.setText("Games");
        btnGamesView.setBorderPainted(false);
        btnGamesView.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGamesView.setIconTextGap(12);
        btnGamesView.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnGenresView.setBackground(new java.awt.Color(22, 27, 34));
        btnGenresView.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnGenresView.setForeground(new java.awt.Color(255, 255, 255));
        btnGenresView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/genres.png"))); // NOI18N
        btnGenresView.setText("Genres");
        btnGenresView.setBorderPainted(false);
        btnGenresView.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGenresView.setIconTextGap(12);
        btnGenresView.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGenresView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenresViewActionPerformed(evt);
            }
        });

        btnListingsView.setBackground(new java.awt.Color(22, 27, 34));
        btnListingsView.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnListingsView.setForeground(new java.awt.Color(255, 255, 255));
        btnListingsView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/listing.png"))); // NOI18N
        btnListingsView.setText("Listings");
        btnListingsView.setBorderPainted(false);
        btnListingsView.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnListingsView.setIconTextGap(12);
        btnListingsView.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnListingsView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnListingsViewMouseClicked(evt);
            }
        });
        btnListingsView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListingsViewActionPerformed(evt);
            }
        });

        btnReviewsView.setBackground(new java.awt.Color(22, 27, 34));
        btnReviewsView.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnReviewsView.setForeground(new java.awt.Color(255, 255, 255));
        btnReviewsView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/review.png"))); // NOI18N
        btnReviewsView.setText("Reviews");
        btnReviewsView.setBorderPainted(false);
        btnReviewsView.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReviewsView.setIconTextGap(12);
        btnReviewsView.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnReviewsView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReviewsViewActionPerformed(evt);
            }
        });

        btnTransactView.setBackground(new java.awt.Color(22, 27, 34));
        btnTransactView.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnTransactView.setForeground(new java.awt.Color(255, 255, 255));
        btnTransactView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/transaction.png"))); // NOI18N
        btnTransactView.setText("Transactions");
        btnTransactView.setBorderPainted(false);
        btnTransactView.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTransactView.setIconTextGap(12);
        btnTransactView.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTransactView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransactViewActionPerformed(evt);
            }
        });

        btnUserView.setBackground(new java.awt.Color(22, 27, 34));
        btnUserView.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnUserView.setForeground(new java.awt.Color(255, 255, 255));
        btnUserView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/users.png"))); // NOI18N
        btnUserView.setText("Users");
        btnUserView.setBorderPainted(false);
        btnUserView.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUserView.setIconTextGap(12);
        btnUserView.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnUserView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUserViewMouseClicked(evt);
            }
        });

        jLogout.setBackground(new java.awt.Color(147, 0, 10));
        jLogout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLogout.setForeground(new java.awt.Color(255, 218, 214));
        jLogout.setText("Logout");
        jLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGamesView, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReviewsView, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGenresView, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTransactView, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnListingsView, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUserView, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(50, 50, 50))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGamesView, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGenresView, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListingsView, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReviewsView, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTransactView, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUserView, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnUserViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserViewMouseClicked
        // TODO add your handling code here:
        if(Session.getRole().equals("admin")) {
            new UserView().setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Anda bukan admin", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUserViewMouseClicked

    private void btnListingsViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListingsViewMouseClicked
        // TODO add your handling code here:
        new ListingView(Session.getUser()).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnListingsViewMouseClicked

    private void btnReviewsViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReviewsViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReviewsViewActionPerformed

    private void btnTransactViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransactViewActionPerformed
        // TODO add your handling code here:
        new TransaksiView(Session.getUser()).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnTransactViewActionPerformed

    private void btnListingsViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListingsViewActionPerformed
        // TODO add your handling code here:
        new ListingView(Session.getUser()).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnListingsViewActionPerformed

    private void jLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLogoutActionPerformed
        // TODO add your handling code here:
        int konfirmasi = JOptionPane.showConfirmDialog(
            this, 
            "Apakah Anda yakin ingin logout?", 
            "Konfirmasi Keluar", 
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE
        );
        
        if (konfirmasi == JOptionPane.YES_OPTION) {
            Session.clear(); 
            new Connection.Login().setVisible(true); 
            this.dispose();
        }
    }//GEN-LAST:event_jLogoutActionPerformed

    private void btnGenresViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenresViewActionPerformed
        // TODO add your handling code here:
        new GenreView(Session.getUser()).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnGenresViewActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGamesView;
    private javax.swing.JButton btnGenresView;
    private javax.swing.JButton btnListingsView;
    private javax.swing.JButton btnReviewsView;
    private javax.swing.JButton btnTransactView;
    private javax.swing.JButton btnUserView;
    private javax.swing.JButton jLogout;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblWelcome;
    // End of variables declaration//GEN-END:variables
}