/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Dashboard;

import Admin.User.UserView;
import javax.swing.JOptionPane;
import util.Session;

/**
 *
 * @author Bintang K
 */
public class DashboardView extends javax.swing.JFrame {

    /**
     * Creates new form DashboardView
     */
    public DashboardView() {
        initComponents();
        if (Session.getRole().equals("admin")) {
            btnUserView.setVisible(true);
        } else {
            btnUserView.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnGamesView = new javax.swing.JButton();
        btnGenresView = new javax.swing.JButton();
        btnListingsView = new javax.swing.JButton();
        btnReviewsView = new javax.swing.JButton();
        btnTransactView = new javax.swing.JButton();
        btnUserView = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(18, 18, 28));

        btnGamesView.setText("Games");

        btnGenresView.setText("Genres");

        btnListingsView.setText("Listings");

        btnReviewsView.setText("Reviews");

        btnTransactView.setText("Transactions");

        btnUserView.setText("Users");
        btnUserView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUserViewMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnListingsView)
                        .addComponent(btnGamesView))
                    .addComponent(btnUserView))
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGenresView)
                    .addComponent(btnReviewsView)
                    .addComponent(btnTransactView))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGamesView)
                    .addComponent(btnGenresView))
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListingsView)
                    .addComponent(btnReviewsView))
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTransactView)
                    .addComponent(btnUserView))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUserViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserViewMouseClicked
        // TODO add your handling code here:
        if(Session.getRole().equals("admin")) {
            new UserView().setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Anda bukan admin", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUserViewMouseClicked

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGamesView;
    private javax.swing.JButton btnGenresView;
    private javax.swing.JButton btnListingsView;
    private javax.swing.JButton btnReviewsView;
    private javax.swing.JButton btnTransactView;
    private javax.swing.JButton btnUserView;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
