/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Buyyer.Review;
import Admin.Transaksi.TransaksiView;
import entity.user;

/**
 *
 * @author Asus
 */
public class ReviewForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ReviewForm.class.getName());
    private user currentUser;
    private TransaksiView parentView;
    private String transactionId;
    /**
     * Creates new form ReviewForm
     */
    public ReviewForm(user usr, TransaksiView parent, String transactionId) {
        initComponents();
        this.currentUser = usr;
        this.parentView = parent;
        this.transactionId = transactionId;
        
        this.setLocationRelativeTo(null); // Membuat form muncul di tengah layar
        this.setTitle("Form Review Transaksi - " + this.transactionId);
        
        // Di sini Anda bisa memanfaatkan variabel 'transactionId' untuk set text ke JLabel, 
        // atau menyimpannya nanti saat tombol 'Simpan/Submit Review' diklik.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
