/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Admin.Game;

import Connection.Koneksi;
import Dashboard.DashboardView;
import entity.user;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asus
 */
public class GameView extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GameView.class.getName());
    private user currentUser;

    /**
     * Creates new form GameView
     */
    public GameView(user usr) {
        this.currentUser = usr;
        initComponents();
        this.setLocationRelativeTo(null);
        checkUserRole();
        load_table();
        
        lblDetailJudul.setText("Detail - Pilih Game");
        lblDetDeveloper.setText("-");
        lblDetGenre.setText("-");
        lblDetPlatform.setText("-");
        lblDetTahun.setText("-");
    }
    
    private void checkUserRole() {
        // 1. Validasi jika objek user kosong/null demi keamanan aplikasi
        if (currentUser == null || currentUser.getRole() == null) {
            btnTambah.setVisible(false);
            btnEdit.setVisible(false);
            btnHapus.setVisible(false);
            return;
        }

        // 2. Periksa apakah role bernilai "admin" (tidak sensitif huruf besar/kecil)
        if (currentUser.getRole().equalsIgnoreCase("admin")) {
            btnTambah.setVisible(true);
            btnEdit.setVisible(true);
            btnHapus.setVisible(true);
        } else {
            // Jika bukan admin (misal: user biasa), sembunyikan semua tombol aksi manajemen game
            btnTambah.setVisible(false);
            btnEdit.setVisible(false);
            btnHapus.setVisible(false);
        }
    }

    public void load_table() {
        // 1. Membuat struktur kolom tabel (Non-editable cell)
        DefaultTableModel model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        model.addColumn("ID");
        model.addColumn("Judul");
        model.addColumn("Genre");
        model.addColumn("Platform");
        model.addColumn("Tahun");

        // 2. Menarik data dari database menggunakan JOIN agar genre terbaca
        try {
            // Query disesuaikan dengan skema tabel asli db_uas_pbo milikmu
            String sql = "SELECT g.game_id, g.title, g.platform, g.release_year, " +
                    "GROUP_CONCAT(gr.name SEPARATOR ', ') AS nama_genre " +
                    "FROM games g " +
                    "LEFT JOIN gamegenre gg ON g.game_id = gg.game_id " +
                    "LEFT JOIN genres gr ON gg.genre_id = gr.id " +
                    "WHERE g.is_delete = FALSE " +
                    "GROUP BY g.game_id " +
                    "ORDER BY g.game_id ASC";

            Connection conn = Koneksi.getConnection();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);

            int totalGame = 0;

            // 3. Looping data hasil query masuk ke dalam model tabel
            while (res.next()) {
                String genre = res.getString("nama_genre");
                if (genre == null || genre.isEmpty()) {
                    genre = "-"; // Antisipasi jika game belum diberi genre
                }

                model.addRow(new Object[] {
                        res.getString("game_id"),
                        res.getString("title"),
                        genre,
                        res.getString("platform"),
                        res.getString("release_year")
                });
                totalGame++;
            }

            // 4. Terapkan model ke JTable komponen (tblGame)
            tblGame.setModel(model);

            // 5. Perbarui komponen label total data game
            lblTotalGame.setText(totalGame + " Game Tercatat");

        } catch (SQLException e) {
            System.err.println("Gagal memuat data tabel: " + e.getMessage());
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal memuat data: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblGame = new javax.swing.JLabel();
        txtCari = new javax.swing.JTextField();
        btnHapus = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        lblSeparator = new javax.swing.JLabel();
        lblTotalGame = new javax.swing.JLabel();
        btDashboard = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGame = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        lblDetailJudul = new javax.swing.JLabel();
        lblInformasi = new javax.swing.JLabel();
        lblDev = new javax.swing.JLabel();
        lblGenre = new javax.swing.JLabel();
        lblPlatform = new javax.swing.JLabel();
        lblTahun = new javax.swing.JLabel();
        lblDetDeveloper = new javax.swing.JLabel();
        lblDetGenre = new javax.swing.JLabel();
        lblDetPlatform = new javax.swing.JLabel();
        lblDetTahun = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(27, 27, 37));

        lblGame.setBackground(new java.awt.Color(139, 128, 173));
        lblGame.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        lblGame.setForeground(new java.awt.Color(139, 128, 173));
        lblGame.setText("Semua Game");

        txtCari.addActionListener(this::txtCariActionPerformed);

        btnHapus.setBackground(new java.awt.Color(27, 27, 37));
        btnHapus.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 0, 0));
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(this::btnHapusActionPerformed);

        btnTambah.setBackground(new java.awt.Color(206, 189, 255));
        btnTambah.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(56, 19, 133));
        btnTambah.setText("+ Tambah Game");
        btnTambah.addActionListener(this::btnTambahActionPerformed);

        btnEdit.setBackground(new java.awt.Color(27, 27, 37));
        btnEdit.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(206, 189, 255));
        btnEdit.setText("Edit");
        btnEdit.addActionListener(this::btnEditActionPerformed);

        lblSeparator.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        lblSeparator.setForeground(new java.awt.Color(139, 128, 173));
        lblSeparator.setText("|");

        lblTotalGame.setBackground(new java.awt.Color(139, 128, 173));
        lblTotalGame.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblTotalGame.setForeground(new java.awt.Color(139, 128, 173));
        lblTotalGame.setText("0 Game Tercatat");

        btDashboard.setBackground(new java.awt.Color(206, 189, 255));
        btDashboard.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        btDashboard.setForeground(new java.awt.Color(56, 19, 133));
        btDashboard.setText("Dashboard");
        btDashboard.addActionListener(this::btDashboardActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblGame)
                .addGap(18, 18, 18)
                .addComponent(lblSeparator)
                .addGap(18, 18, 18)
                .addComponent(lblTotalGame)
                .addGap(63, 63, 63)
                .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(btDashboard)
                .addGap(18, 18, 18)
                .addComponent(btnTambah)
                .addGap(47, 47, 47)
                .addComponent(btnEdit)
                .addGap(18, 18, 18)
                .addComponent(btnHapus)
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblGame, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblSeparator)
                        .addComponent(lblTotalGame, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnHapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCari)
                            .addComponent(btnTambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        tblGame.setBackground(new java.awt.Color(31, 31, 41));
        tblGame.setForeground(new java.awt.Color(202, 196, 212));
        tblGame.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Judul", "Genre", "Platform", "Tahun"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblGame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGameMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblGame);

        jPanel2.setBackground(new java.awt.Color(41, 41, 52));

        lblDetailJudul.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblDetailJudul.setForeground(new java.awt.Color(206, 189, 255));
        lblDetailJudul.setText("Detail - Elden Ring");

        lblInformasi.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lblInformasi.setForeground(new java.awt.Color(206, 189, 255));
        lblInformasi.setText("Informasi Game");

        lblDev.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lblDev.setForeground(new java.awt.Color(206, 189, 255));
        lblDev.setText("Developer");

        lblGenre.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lblGenre.setForeground(new java.awt.Color(206, 189, 255));
        lblGenre.setText("Genre");

        lblPlatform.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lblPlatform.setForeground(new java.awt.Color(206, 189, 255));
        lblPlatform.setText("Platform");

        lblTahun.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lblTahun.setForeground(new java.awt.Color(206, 189, 255));
        lblTahun.setText("Tahun");

        lblDetDeveloper.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lblDetDeveloper.setForeground(new java.awt.Color(206, 189, 255));

        lblDetGenre.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lblDetGenre.setForeground(new java.awt.Color(206, 189, 255));

        lblDetPlatform.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lblDetPlatform.setForeground(new java.awt.Color(206, 189, 255));

        lblDetTahun.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lblDetTahun.setForeground(new java.awt.Color(206, 189, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblDetailJudul)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblGenre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblDetGenre, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblDev)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblDetDeveloper, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblInformasi)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblTahun)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblDetTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblPlatform)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblDetPlatform, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(967, 967, 967))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(lblDetailJudul)
                .addGap(18, 18, 18)
                .addComponent(lblInformasi)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDev)
                    .addComponent(lblDetDeveloper))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGenre)
                    .addComponent(lblDetGenre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlatform)
                    .addComponent(lblDetPlatform))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTahun)
                    .addComponent(lblDetTahun))
                .addGap(69, 69, 69))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDashboardActionPerformed
        // TODO add your handling code here:
        new DashboardView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btDashboardActionPerformed

    private void tblGameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGameMouseClicked
        // TODO add your handling code here:
       int row = tblGame.getSelectedRow();
        if (row == -1) {
            return; // Jaga-jaga jika kliknya tidak valid atau di area kosong
        }

        // 2. Ambil game_id dari kolom pertama (index 0)
        String gameId = tblGame.getValueAt(row, 0).toString();

        // 3. Ambil data detail lengkap langsung dari database berdasarkan gameId
        try {
            String sql = "SELECT * FROM games WHERE game_id = '" + gameId + "'";
            
            Connection conn = Koneksi.getConnection();
            java.sql.Statement st = conn.createStatement();
            java.sql.ResultSet res = st.executeQuery(sql);

            if (res.next()) {
                // 4. Set teks komponen detail sesuai data dari database dengan nama kolom yang benar
                lblDetailJudul.setText("Detail - " + res.getString("title")); // Diubah dari "judul" ke "title"
                lblDetDeveloper.setText(res.getString("developer"));
                
                // Mengambil genre langsung dari kolom ke-3 (index 2) tabel GUI karena gabungan string GROUP_CONCAT
                lblDetGenre.setText(tblGame.getValueAt(row, 2).toString()); 
                
                lblDetPlatform.setText(res.getString("platform"));
                lblDetTahun.setText(res.getString("release_year")); // Diubah dari "tahun" ke "release_year"
            }

            res.close();
            st.close();
        } catch (java.sql.SQLException e) {
            logger.log(java.util.logging.Level.SEVERE, "Gagal mengambil detail game", e);
            javax.swing.JOptionPane.showMessageDialog(this, "Error memuat detail: " + e.getMessage());
        }
    }//GEN-LAST:event_tblGameMouseClicked

    private void txtCariActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtCariActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtCariActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        int row = tblGame.getSelectedRow();
        if (row == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Silakan pilih game yang ingin dihapus!");
            return;
        }

        // 2. Ambil ID Game dan Judul
        String gameId = tblGame.getValueAt(row, 0).toString();
        String judulGame = tblGame.getValueAt(row, 1).toString();

        // 3. Konfirmasi Hapus
        int konfirmasi = javax.swing.JOptionPane.showConfirmDialog(this, 
                "Apakah Anda yakin ingin menghapus game '" + judulGame + "'?\n" +
                "Data game ini akan disembunyikan dari aplikasi.", 
                "Konfirmasi Hapus", javax.swing.JOptionPane.YES_NO_OPTION);

        if (konfirmasi == javax.swing.JOptionPane.YES_OPTION) {
            try {
                // 4. Update is_delete menjadi TRUE (Soft Delete)
                // Menggunakan query UPDATE, bukan DELETE
                String sql = "UPDATE games SET is_delete = TRUE WHERE game_id = ?";

                Connection conn = Koneksi.getConnection();
                java.sql.PreparedStatement st = conn.prepareStatement(sql);
                st.setString(1, gameId);

                int hasil = st.executeUpdate();

                if (hasil > 0) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Game berhasil dihapus!");
                    load_table(); // Refresh tabel agar game hilang dari tampilan
                }

                st.close();
            } catch (java.sql.SQLException e) {
                logger.log(java.util.logging.Level.SEVERE, "Gagal menghapus game", e);
                javax.swing.JOptionPane.showMessageDialog(this, "Gagal menghapus: " + e.getMessage());
            }
        }
    }// GEN-LAST:event_btnHapusActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        GameForm form = new GameForm(currentUser, this);
        form.setVisible(true);
    }// GEN-LAST:event_btnTambahActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:

    }// GEN-LAST:event_btnEditActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDashboard;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambah;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDetDeveloper;
    private javax.swing.JLabel lblDetGenre;
    private javax.swing.JLabel lblDetPlatform;
    private javax.swing.JLabel lblDetTahun;
    private javax.swing.JLabel lblDetailJudul;
    private javax.swing.JLabel lblDev;
    private javax.swing.JLabel lblGame;
    private javax.swing.JLabel lblGenre;
    private javax.swing.JLabel lblInformasi;
    private javax.swing.JLabel lblPlatform;
    private javax.swing.JLabel lblSeparator;
    private javax.swing.JLabel lblTahun;
    private javax.swing.JLabel lblTotalGame;
    private javax.swing.JTable tblGame;
    private javax.swing.JTextField txtCari;
    // End of variables declaration//GEN-END:variables
}
