/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Admin.Genre;

import entity.user;
import entity.genre; 
import interfc.GenreInterfc;
import implement.GenreImpl;
import javax.swing.JOptionPane;
import java.sql.SQLException;

/**
 *
 * @author Asus
 */
public class GenreForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GenreForm.class.getName());
     private user currentUser;
     private GenreView genreView;
     
     private GenreInterfc genreService = new GenreImpl();
    private genre selectedGenre; // Menyimpan data genre yang akan diedit
    private boolean isEditMode = false; // Flag penanda mode form
    private String generatedId;
    
    /**
     * Creates new form GenreForm
     */
    public GenreForm(user currentUser, GenreView parentView) {
        initComponents();
        this.currentUser = currentUser;
        this.genreView = parentView;
        this.isEditMode = false;
        
        lbJudulForm.setText("Tambah Genre Baru");
        prepareAutoId(); // Generate ID otomatis saat form dibuka
    }
    
    /**
     * CONSTRUCTOR 2: Untuk Mode EDIT DATA (Overloading)
     */
    public GenreForm(user currentUser, GenreView parentView, genre g) {
        initComponents();
        this.currentUser = currentUser;
        this.genreView = parentView;
        this.selectedGenre = g;
        this.isEditMode = true;
        
        lbJudulForm.setText("Edit Data Genre");
        // Isi textfield dengan nama genre yang dipilih dari tabel parentView
        tfNamaGenre.setText(g.getNamaGenre()); 
    }
    
    private void prepareAutoId() {
        try {
            this.generatedId = genreService.generateNewGenreId();
        } catch (SQLException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelUtama = new javax.swing.JPanel();
        lbJudulForm = new javax.swing.JLabel();
        lbNamaGenre = new javax.swing.JLabel();
        tfNamaGenre = new javax.swing.JTextField();
        btSimpan = new javax.swing.JButton();
        btBatal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        panelUtama.setBackground(new java.awt.Color(41, 41, 52));

        lbJudulForm.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        lbJudulForm.setForeground(new java.awt.Color(255, 255, 255));
        lbJudulForm.setText("Tambah / Edit Genre");

        lbNamaGenre.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lbNamaGenre.setForeground(new java.awt.Color(184, 184, 204));
        lbNamaGenre.setText("Nama Genre :");

        tfNamaGenre.setBackground(new java.awt.Color(24, 24, 35));
        tfNamaGenre.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tfNamaGenre.setForeground(new java.awt.Color(255, 255, 255));
        tfNamaGenre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 45, 60)));

        btSimpan.setBackground(new java.awt.Color(60, 221, 199));
        btSimpan.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btSimpan.setForeground(new java.awt.Color(17, 17, 29));
        btSimpan.setText("Simpan");
        btSimpan.setBorder(null);
        btSimpan.addActionListener(this::btSimpanActionPerformed);

        btBatal.setBackground(new java.awt.Color(208, 59, 70));
        btBatal.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btBatal.setForeground(new java.awt.Color(255, 255, 255));
        btBatal.setText("Batal");
        btBatal.setBorder(null);
        btBatal.addActionListener(this::btBatalActionPerformed);

        javax.swing.GroupLayout panelUtamaLayout = new javax.swing.GroupLayout(panelUtama);
        panelUtama.setLayout(panelUtamaLayout);
        panelUtamaLayout.setHorizontalGroup(
            panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUtamaLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbJudulForm)
                    .addComponent(lbNamaGenre)
                    .addComponent(tfNamaGenre, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUtamaLayout.createSequentialGroup()
                        .addComponent(btSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        panelUtamaLayout.setVerticalGroup(
            panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUtamaLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lbJudulForm)
                .addGap(24, 24, 24)
                .addComponent(lbNamaGenre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfNamaGenre, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSimpanActionPerformed
        // TODO add your handling code here:
        String namaGenreInput = tfNamaGenre.getText().trim();
        
        // Validasi input tidak boleh kosong
        if (namaGenreInput.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama genre tidak boleh kosong!", "Validasi Gagal", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            if (isEditMode) {
                // Skenario 1: Proses Jalur UPDATE DATA
                selectedGenre.setNamaGenre(namaGenreInput);
                
                boolean berhasilUpdate = genreService.updateGenre(selectedGenre);
                if (berhasilUpdate) {
                    JOptionPane.showMessageDialog(this, "Data genre berhasil diperbarui!");
                    genreView.loadData(); // Memicu refresh tabel di GenreView secara realtime
                    this.dispose(); // Tutup form input
                } else {
                    JOptionPane.showMessageDialog(this, "Gagal memperbarui data genre.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                // Skenario 2: Proses Jalur INSERT DATA BARU
                genre gBaru = new genre();
                gBaru.setIdGenre(generatedId);
                gBaru.setNamaGenre(namaGenreInput);
                
                boolean berhasilInsert = genreService.insertGenre(gBaru);
                if (berhasilInsert) {
                    JOptionPane.showMessageDialog(this, "Genre baru berhasil ditambahkan!");
                    genreView.loadData(); // Memicu refresh tabel di GenreView secara realtime
                    this.dispose(); // Tutup form input
                } else {
                    JOptionPane.showMessageDialog(this, "Gagal menambahkan genre baru.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan pada database: " + ex.getMessage(), "Error Database", JOptionPane.ERROR_MESSAGE);
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btSimpanActionPerformed

    private void btBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBatalActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btBatalActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBatal;
    private javax.swing.JButton btSimpan;
    private javax.swing.JLabel lbJudulForm;
    private javax.swing.JLabel lbNamaGenre;
    private javax.swing.JPanel panelUtama;
    private javax.swing.JTextField tfNamaGenre;
    // End of variables declaration//GEN-END:variables
}
